source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '16.0'

target 'BlueToothTool_Example' do
  pod 'BlueToothTool', :path => '../'

  # Debug
  pod 'LookinServer', '1.2.8', :subspecs => ['SwiftAndNoHook'], :configurations => ['Debug']
  pod 'DoraemonKit', '3.1.7', :configurations => ['Debug']

  target 'BlueToothTool_Tests' do
    inherit! :search_paths

    
  end
end


#Pods config
#Fix Xcode14 Bundle target error
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['ENABLE_BITCODE'] = "NO"
            config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
            config.build_settings['SWIFT_VERSION'] = '5'
            # Pod中的库，不允许自动生成证书
            config.build_settings['CODE_SIGN_STYLE'] = 'Manual'
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
    end
end
